### ISSUE TITLE
HTML,CSS

### ISSUE THREAD

**Issue by Saccharin01** [Saccharin01/COOPTest#12]
![화면 캡처 2024-06-05 023315](https://github.com/Saccharin01/COOPTest/assets/165748104/822073ee-6ace-40f5-af63-d7c7955dab84)

작업하신 내용을 바탕으로 단위 검증을 진행했습니다.
해당 과정 중에 라이브 서버 확장 프로그램을 이용하였고, 검증 과정에서 오류가 발생했음을 확인했습니다.
점검 후 수정 부탁드립니다.

HTML 요소 스타일링 중 빠트린 부분이 있는지 점검 부탁드립니다.

html, css 작업 중 확장 프로그램 "라이브서버"를 이용해서 단위 테스트 혹은 프로세스 진행도를 같이 점검 부탁드립니다.

**Comment by koohrim12** [comment]
알겠습니다. 확인해보겠습니다.

**Comment by Saccharin01** [comment]
필요한 부분 외의 코맨드는 슬랙을 이용해주세요. 본 이슈는 작업 완료 전까지 닫히면 안됩니다

**Comment by Saccharin01** [comment]
회원가입 절차에는 몇가지 추가적인 정보가 필요합니다
팀장의 생각으로는 아이디와 패스워드 외에도 입력한 패스워드가 맞는지 검증해줄 수단이 필요하다고 생각합니다.
우리가 흔히 마주할 수 있는 회원가입 란에는

아이디 입력
비밀번호 입력
비밃번호 확인

처럼 비밀번호를 올바르게 입력했는지 알아볼 수 있는 수단이 존재합니다. 본 상황에서, 팀장 또한 이러한 기능이 필요하다고 생각합니다.

팀장의 생각은 다음과 같습니다.
1. 비밀번호입력 / 비밀번호 확인 처럼 input 태그가 하나 더 있어야 한다고 생각합니다.
2. css 라인이 너무 부실합니다. 예시를 첨부해드리겠습니다. 본 예시가 정답이 아닙니다. 제작자 분의 충분한 상상력을 발휘하셔서 더 이쁘게 꾸며주셨으면 좋겠습니다.
3. html 오류가 아직 사라지지 않았습니다. 해당 오류는 password라는 input type이 설정 되었을 경우, 자동완성 기능이 활성화 되어있기 때문에 발생하는 문제로 생각됩니다. 확인 후에 수정 부탁드립니다.

 
![Frame 1 (2)](https://github.com/Saccharin01/COOPTest/assets/165748104/89bb4c45-4120-4773-bebb-c9ee0153dcf2)
