### ISSUE TITLE
javaScriptIssue

### ISSUE THREAD

**Issue by Saccharin01** [Saccharin01/COOPTest#14]
작업하신 내용을 모두 살펴보았습니다.

현재 작업중이신 내용은, 클라이언트 단에서 핸들링 하기엔 부담스러운 부분이 있는 로직으로 판단됩니다.
때문에, 팀장의 의견은 다음과 같습니다.

1. 임의 변수 a에 빈 배열을 할당 해주세요
2. 빈 배열 속에 DOM API를  통해서 input 태그의 갯수 만큼 false 값을 넣어주세요
3. DOM API를 이용해서 유저가 입력한 정보를 조회 해주세요
4. 조회 된 정보의 데이터 타입이 "문자열"인지 확인해주세요
5. 데이터 타입이 문자열이 맞다면 false 값 중 하나를 true로 바꿔주세요

**Comment by Saccharin01** [comment]
제출하신 내용 상에서 발생하는 여러 로직 에러들을 발견했습니다.
현재 제작중인 html 파일의 경우 form 혹은 button 의 type은 submit 입니다.
서버에 유저가 입력한 데이터를 제출하는 로직을 띄고 있기 때문으로 사료됩니다만, submit의 경우 html을 새로고침 하는 기본 행동 양식을 가지고 있습니다.

때문에 임의 배열 a에 특정한 값을 할당한다고 해도 새로이 코드를 실행하는 독특한 내부 로직 때문에 console.log(임의배열a) 라는 코드를 실행 해봐도 늘 초기 할당한 값만 보여지게 될 겁니다.
해당 부분에 대한 로직을 재점검 부탁드립니다.

또한 button에 이벤트 리스너를 부여해놓으셨는데, html 문서 상에서는 버튼 요소가 감지되지 않는 문제가 존재합니다. 해당 부분을 html 작업자와 교차 검증하시어 업무 수행을 부탁드립니다.

**Comment by yooeuddeum** [comment]
오늘 push 넣은 branch는 주석 처리에 기입한 설명처럼 브라우저상에서만 인터페이스 차원에서 구현한 방식이고,
서버에 보낼 수 있는 코드로 다시 수정해 볼 생각입니다. 이슈 건은 의견을 수령해서 잘 참고하고 로직을 만들어 볼 생각이고,
문제 삼으셨던 HTML을 새로 고침하고 기본 동작 양식을 제출 하는 형식 계속해서 실행하고 초기 값만 보여주는 부분에 있어서는 이벤트 리스너를 사용했을때  submit으로 뒀을때 자체적으로 발생하는 event를 활용해서 preventdefault() 메서드를 사용하게 된다면 그 부분을 보안할수 있을것 같습니다. 예시( event.preventdefault( ) ) 이것을 사용하면 현재 이슈 거리는 해결 될꺼라고 생각은 합니다. 저 역시 그 부분에 어느정도 이슈가 될 부분이라 생각하여 찾아보고 저 메서드를 알게 되었습니다. 한번 확인해보시고 판단해보세용 팀좡님

**Comment by Saccharin01** [comment]
말씀해주신 event.preventdefault( ) 의 경우 이벤트의 흐름을 강제로 막는 기능을 하는 메서드입니다. 해당 매서드의 접근 자체는 나쁘지 않은 것 같습니다만, 제 로컬에서 테스트 해 본 결과 증상 자체는 동일하게 발생하고 있습니다.

이는, 이벤트를 막아내는 것이 아니라 html이 자체적으로 submit을 해주기 때문입니다.

본 문서 상 form 태그는 자식으로 div 두 개와 button 하나를 두고 있습니다.
 버튼 태그에는 submit 이라는 타입이 적용되어 있기 때문에 이벤트를 막는다고 해도 작업자 분의 로직이 성립되지 않는 것 같습니다.
아무래도 팀장이 판단하기에 작업자 분의 접근 방식은 조금 더 서버 스럽습니다. 다시 말하자면 백 엔드 단의 작업으로 접근하고 계신 것 같습니다.

말씀드리기 조심스럽습니다만, 현재 작업자 분에게 할당되어 있는 작업은 html, css를 제어하는 자바스크립트를 작성하는 작업입니다.

빈 배열에 유저가 입력한 정보가 저장이 되고 그 정보를 핸들링 하는 작업을 수행하는 것은 가능합니다.
하지만 현 프로젝트 상 "회원가입"을 주제로 하고 있기 때문에 html 문서에서 submit 작동을 하는 것은 어찌보면 굉장히 당연한 일입니다.
제출을 하지 않으면 정보가 저장되지 않기 때문이죠.

해서, 팀장의 의견은 다음과 같습니다.

1. html 작업자 분에게 피그마로 제작한 html 레이아웃 샘플을 보내드렸습니다. 이를 통해서 저희는 자바스크립트로 핸들링 할 수 있는 여러가지 요소들을 획득 했습니다.

![Frame 1 (2)](https://github.com/Saccharin01/COOPTest/assets/165748104/0ea131a9-bf90-4908-9486-094572e03324)

이 상황에서, div 3 개 위로 마우스가 올라가면, 마우스가 올라간 div 의 색상을 다르게 해서 시인성을 올리는 작업을 부탁드리고자 합니다.

혹여, 작업자 분께서 욕심이 나신다면 xindex로 떠있는 저 div를 드롭다운 메뉴로 구성 해보시는 것도 좋은 방법 중 하나라고 생각합니다.
